# Generated by Django 5.2.9 on 2025-12-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Earl Lawrence R. Sigue', max_length=100)),
                ('title', models.CharField(default='Information Technology Student | Aspiring Sound Engineer', max_length=200)),
                ('bio', models.TextField(default="Hello! I'm Earl, a hardworking IT student with a passion for technology, sound engineering, and web development.")),
                ('profile_pic', models.ImageField(upload_to='profile_pics/')),
            ],
        ),
    ]
